version: "3"
services:
  raytracer-service:
    container_name: raytracer-container
    image: raytracer-image
    build:
      context: ./
      dockerfile: docker/Dockerfile.raytracer
    ports:
      - 8080:80
    restart: always
    environment:
      - DISPLAY=:0
