version: "3"
services:
  frontend-service:
    container_name: frontend-container
    image: frontend-image
    build:
      context: ./
      dockerfile: docker/Dockerfile.frontend
    ports:
      - 8080:80
    restart: always
    environment:
      - DISPLAY=:0
