FROM dorowu/ubuntu-desktop-lxde-vnc
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN apt-get update && \
    apt-get install -y \
    cmake \
    qtbase5-dev \
    build-essential

WORKDIR /app

COPY frontend/. .

RUN make build

EXPOSE 8080
ENV DISPLAY=:0

RUN chmod +x startup.sh
CMD ["startup.sh"]
