#pragma once

#include "utils.h"
#include "HitRecord.h"
#include "Ray.h"
#include "Image.h"
#include "Color.h"
#include "ColorManipulator.h"
#include "Camera.h"
#include "Scene.h"
#include "Renderer.h"
#include "Lambertian.h"
#include "Metal.h"
#include "Dielectric.h"
#include "Sphere.h"
#include "Cuboid.h"
#include "Cylinder.h"
