#pragma once

#include "utils.h"
#include "HitRecord.h"
#include "Ray.h"
#include "Image.h"
#include "Color.h"
#include "ColorManipulator.h"
#include "Camera.h"
#include "Scene.h"
#include "Renderer.h"
#include "MaterialLambertian.h"
#include "MaterialMetal.h"
#include "MaterialDielectric.h"
#include "ObjectSphere.h"
#include "ObjectCuboid.h"
#include "ObjectCylinder.h"
#include "Example.h"
